/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./views/BaseHeader.vue')['default']
    CoordinateQueryTool: typeof import('./components/query-tools/CoordinateQueryTool.vue')['default']
    DrawAndPickCoordinateTool: typeof import('./components/draw-tools/DrawAndPickCoordinateTool.vue')['default']
    DrawFromFileTool: typeof import('./components/draw-tools/DrawFromFileTool.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    EleQueryTool: typeof import('./components/query-tools/EleQueryTool.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LaneKeyPointQueryTool: typeof import('./components/query-tools/LaneKeyPointQueryTool.vue')['default']
    LocalMapLoader: typeof import('./components/megmap-management/LocalMapLoader.vue')['default']
    LocationQueryTool: typeof import('./components/query-tools/LocationQueryTool.vue')['default']
    MapConnectivityValidationTool: typeof import('./components/result-check-tools/MapConnectivityValidationTool.vue')['default']
    MegMap: typeof import('./components/MegMap.vue')['default']
    MegMapView: typeof import('./views/MegMapView.vue')['default']
    OnlineMapList: typeof import('./components/megmap-management/OnlineMapList.vue')['default']
    PathPlanningValidationTool: typeof import('./components/result-check-tools/PathPlanningValidationTool.vue')['default']
    TestResultValidationTool: typeof import('./components/result-check-tools/TestResultValidationTool.vue')['default']
    ToolSide: typeof import('./components/ToolSide.vue')['default']
    WlxVis: typeof import('./components/megmap-management/WlxVis.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
